name: fmt

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

jobs:
  fmt:
    runs-on: ubuntu-20.04

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v3
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        base: main
        token: ${{ secrets.TOKEN }}
        branch: fmt
        delete-branch: true
        title: ${{ github.event.head_commit.message }}
        commit-message: ${{ github.event.head_commit.message }}